### ISSUE TITLE
Not supporting Python 3.x version

### ISSUE THREAD

**Issue by manjusha24** [htarevern/salesforce-python-sdk#10]
when tried to install in Python3.5, it runs but when importing it throws below error.
`Python 3.5.1 (default, Jan 22 2016, 08:52:08) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import salesforce as sf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users//SourceCode/environments/lib/python3.5/site-packages/salesforce/__init__.py", line 1, in <module>
    from salesforce.api import Salesforce
  File "/Users/SourceCode/environments/lib/python3.5/site-packages/salesforce/api.py", line 1, in <module>
    from salesforceSoapApi import SalesforceSoapAPI
ImportError: No module named 'salesforceSoapApi'`

**Comment by mikep2016** [comment]
This is still an issue.

>>> import salesforce
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\data\python\project\env\lib\site-packages\salesforce\__init__.py", line 1, in <module>
    from salesforce.api import Salesforce
  File "C:\data\python\project\env\lib\site-packages\salesforce\api.py", line 1, in <module>
    from salesforceSoapApi import SalesforceSoapAPI
ImportError: No module named 'salesforceSoapApi'

**Comment by christopherreece** [comment]
Yep. I have this issue too. But in 3.6
